// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'colorBrand': string;
  'colorLinkHover': string;
  'root': string;
  'theme': string;
}
export const cssExports: CssExports;
export default cssExports;
