// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace HomeCssNamespace {
  export interface IHomeCss {
    home: string;
  }
}

declare const HomeCssModule: HomeCssNamespace.IHomeCss;

export = HomeCssModule;
