// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'breakpointSm': string;
  'main': string;
  'mainAndFooter': string;
  'size2x': string;
  'size4x': string;
  'theme': string;
}
export const cssExports: CssExports;
export default cssExports;
