// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace BadgeCssNamespace {
  export interface IBadgeCss {
    root: string;
  }
}

declare const BadgeCssModule: BadgeCssNamespace.IBadgeCss;

export = BadgeCssModule;
