// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace BadgeCollectionCssNamespace {
  export interface IBadgeCollectionCss {
    badge: string;
    root: string;
  }
}

declare const BadgeCollectionCssModule: BadgeCollectionCssNamespace.IBadgeCollectionCss;

export = BadgeCollectionCssModule;
