// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'colorBackgroundDefaultLight': string;
  'colorBrand': string;
  'container': string;
  'header': string;
  'size2x': string;
  'size3x': string;
  'theme': string;
}
export const cssExports: CssExports;
export default cssExports;
