// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace ProjectsCssNamespace {
  export interface IProjectsCss {
    header: string;
    projectEven: string;
    projectOdd: string;
  }
}

declare const ProjectsCssModule: ProjectsCssNamespace.IProjectsCss;

export = ProjectsCssModule;
