// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'SmUp': string;
  'Xs': string;
  'breakpointXs': string;
  'theme': string;
}
export const cssExports: CssExports;
export default cssExports;
