// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace TwoColumnLayoutCssNamespace {
  export interface ITwoColumnLayoutCss {
    root: string;
  }
}

declare const TwoColumnLayoutCssModule: TwoColumnLayoutCssNamespace.ITwoColumnLayoutCss;

export = TwoColumnLayoutCssModule;
