// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace LazyPictureCssNamespace {
  export interface ILazyPictureCss {
    fadeIn: string;
    root: string;
  }
}

declare const LazyPictureCssModule: LazyPictureCssNamespace.ILazyPictureCss;

export = LazyPictureCssModule;
