// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'back': string;
  'breakpointXs': string;
  'colorBackgroundNavigation': string;
  'colorLinkDefault': string;
  'colorLinkHover': string;
  'hamburger': string;
  'link': string;
  'listReset': string;
  'menuBars': string;
  'menuInput': string;
  'menuLabel': string;
  'menuList': string;
  'root': string;
  'sizeHeaderHeight': string;
  'theme': string;
}
export const cssExports: CssExports;
export default cssExports;
