// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'breakpointXs': string;
  'colorBackgroundNavigation': string;
  'fadeOut': string;
  'list': string;
  'listReset': string;
  'root': string;
  'shadowSvgIconCssFilter': string;
  'size2x': string;
  'solid': string;
  'theme': string;
}
export const cssExports: CssExports;
export default cssExports;
