// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bar': string;
  'foo': string;
  'navFaded': string;
  'navSolid': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
