// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace HeaderCssNamespace {
  export interface IHeaderCss {
    'nav-faded': string;
    'nav-solid': string;
    root: string;
  }
}

declare const HeaderCssModule: HeaderCssNamespace.IHeaderCss;

export = HeaderCssModule;
