// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace HeaderCssNamespace {
  export interface IHeaderCss {
    navFaded: string;
    navSolid: string;
    root: string;
  }
}

declare const HeaderCssModule: HeaderCssNamespace.IHeaderCss;

export = HeaderCssModule;
