// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace IntroCssNamespace {
  export interface IIntroCss {
    arrowDownLink: string;
    description: string;
    headline: string;
    highlightText: string;
    iconList: string;
    platformIcon: string;
    root: string;
  }
}

declare const IntroCssModule: IntroCssNamespace.IIntroCss;

export = IntroCssModule;
