// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrowDownLink': string;
  'colorBrand': string;
  'colorTextDefault': string;
  'description': string;
  'headline': string;
  'highlightText': string;
  'iconList': string;
  'platformIcon': string;
  'root': string;
  'size1x': string;
  'size2x': string;
  'size4x': string;
  'theme': string;
}
export const cssExports: CssExports;
export default cssExports;
