// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrowDownLink': string;
  'description': string;
  'headline': string;
  'highlightText': string;
  'iconList': string;
  'platformIcon': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
