// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace AboutCssNamespace {
  export interface IAboutCss {
    photoContainer: string;
    root: string;
  }
}

declare const AboutCssModule: AboutCssNamespace.IAboutCss;

export = AboutCssModule;
