// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace FooterCssNamespace {
  export interface IFooterCss {
    root: string;
  }
}

declare const FooterCssModule: FooterCssNamespace.IFooterCss;

export = FooterCssModule;
