// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'breakpointSm': string;
  'colorBrand': string;
  'colorTextHighlight': string;
  'list': string;
  'listReset': string;
  'root': string;
  'size2x': string;
  'size3x': string;
  'theme': string;
}
export const cssExports: CssExports;
export default cssExports;
