// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'delimiter': string;
  'previewPictureContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
