// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'breakpointSm': string;
  'externalLinkIcon': string;
  'previewPictureContainer': string;
  'rightColumn': string;
  'size6x': string;
  'theme': string;
}
export const cssExports: CssExports;
export default cssExports;
